// Get all bookings
GET http://localhost:8080/bookings
Authorization: Bearer {{jwt}}

###

// Get one specific booking
GET http://localhost:8080/bookings/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}

###

// Create a new booking

POST http://localhost:8080/bookings
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "id": "3c13c533-fbac-4881-b94d-f95cb2ef16c2",
  "name": "Mike Finger",
  "booking_type": "AFTERNOON",
  "status": "PENDING"
}

###

// Approve a new booking
PUT http://localhost:8080/bookings/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Gus Gusman",
  "id": "b8160463-01a0-4c7a-bd46-5b3716dbe4c6",
  "booking_type": "AFTERNOON",
  "status": "APPROVED"
}

###

// Deny a new booking
PUT http://localhost:8080/bookings/413e2297-b84b-42ef-97ed-16a8a9d1d671
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "id": "413e2297-b84b-42ef-97ed-16a8a9d1d671",
  "name": "Jesse Meier",
  "booking_type": "DAY",
  "status": "DENIED"
}

###

// Update one specific booking
PUT http://localhost:8080/bookings/b8160463-01a0-4c7a-bd46-5b3716dbe4c6
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Dave Daveran",
  "id": "3c13c533-fbac-4881-b94d-f95cb2ef16c8",
  "booking_type": "MORNING",
  "status": "PENDING"
}

###

// Delete one specific and existing booking
DELETE http://localhost:8080/bookings/b8160463-01a0-4c7a-bd46-5b3716dbe4c6
Authorization: Bearer {{jwt}}

###

// List all members
GET http://localhost:8080/member
Authorization: Bearer {{jwt}}

###

// Delete one specific and existing Member
DELETE http://localhost:8080/member/9135f12e-1b66-4ee6-bbae-df37303cc154
Authorization: Bearer {{jwt}}

// Unsubscribe from newsletter

###

PUT http://localhost:8080/member/9135f12e-1b66-4ee6-bbae-df37303cc154
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "id": "9135f12e-1b66-4ee6-bbae-df37303cc154",
  "username": "admin",
  "email": "admin@admin.ch",
  "firstname": "admin",
  "lastname": "administator",
  "passwordHash": "$2a$10$aDD6I9Ej5.W8busvlsdPx.JvMWyJX8cOeOfVb.3q73KH2swww/N9C",
  "newsletter": false,
  "isAdmin": true
}

###

// Subscribe from newsletter
PUT http://localhost:8080/member/9135f12e-1b66-4ee6-bbae-df37303cc154
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "id": "9135f12e-1b66-4ee6-bbae-df37303cc154",
  "username": "admin",
  "email": "admin@admin.ch",
  "firstname": "admin",
  "lastname": "administator",
  "passwordHash": "$2a$10$aDD6I9Ej5.W8busvlsdPx.JvMWyJX8cOeOfVb.3q73KH2swww/N9C",
  "newsletter": true,
  "isAdmin": true
}